-- Run against a disposable migrated database. Every assertion is read-only and the transaction is rolled back.
begin;
do $$
declare d record;
begin
  if to_regclass('public.schedule_booking_blocks') is null or to_regclass('public.schedule_booking_block_rooms') is null then raise exception 'tables missing'; end if;
  if (select atttypid <> 'uuid'::regtype from pg_attribute where attrelid='public.schedule_booking_block_rooms'::regclass and attname='room_id') then raise exception 'room_id must be uuid'; end if;
  if not exists(select 1 from pg_class where oid='public.schedule_booking_blocks'::regclass and relrowsecurity) then raise exception 'RLS disabled'; end if;
  if exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name like 'schedule_booking_block%' and grantee in ('anon','authenticated') and privilege_type in ('INSERT','UPDATE','DELETE')) then raise exception 'direct mutations granted'; end if;
  if exists(select 1 from pg_policies where schemaname='public' and tablename like 'schedule_booking_block%' and cmd in ('INSERT','UPDATE','DELETE','ALL')) then raise exception 'mutation policy exists'; end if;
  if not exists(select 1 from pg_proc where oid='public.crm_fetch_schedule_booking_blocks()'::regprocedure and prosecdef and array_to_string(proconfig,',') like '%search_path=public%') then raise exception 'fetch hardening missing'; end if;
  if not exists(select 1 from information_schema.triggers where event_object_schema='public' and event_object_table='room_bookings' and action_timing='BEFORE' and event_manipulation='INSERT') or not exists(select 1 from information_schema.triggers where event_object_schema='public' and event_object_table='room_bookings' and event_manipulation='UPDATE') then raise exception 'booking trigger missing'; end if;
  if not public.crm_valid_iso_weekdays(array[1,7]::smallint[]) or public.crm_valid_iso_weekdays(array[1,1]::smallint[]) then raise exception 'weekday validation broken'; end if;
  if not ('10:00'::time < '11:00'::time and '10:00'::time < '11:00'::time) or ('10:00'::time < '10:00'::time) then raise exception 'half-open overlap broken'; end if;
  if not public.crm_schedule_booking_occurs_on('2026-01-01','2027-01-01','daily') then raise exception 'open-ended daily semantics broken'; end if;
  if not public.crm_schedule_booking_occurs_on('2026-01-01','2026-12-31','weekly') then raise exception 'open-ended weekly semantics broken'; end if;
  if public.crm_schedule_booking_occurs_on('2026-01-31','2026-02-28','monthly') or not public.crm_schedule_booking_occurs_on('2026-01-31','2026-03-31','monthly') then raise exception 'month-end recurrence shifted'; end if;
  if public.crm_schedule_booking_recurrence_hits_block('2026-01-01',null,'none','9000-01-01','9999-12-31',array[1,2,3,4,5,6,7]::smallint[]) then raise exception 'one-off scanned a future block'; end if;
  if not public.crm_schedule_booking_recurrence_hits_block('2026-01-01',null,'daily','9000-01-01','9999-12-31',array[1]::smallint[]) then raise exception 'long daily recurrence missed'; end if;
  if not public.crm_schedule_booking_recurrence_hits_block('2026-01-01',null,'weekly','9000-01-01','9999-12-31',array[4]::smallint[]) then raise exception 'long weekly recurrence missed'; end if;
  if public.crm_schedule_booking_recurrence_hits_block('2026-01-31',null,'monthly','2026-02-28','2026-02-28',array[6]::smallint[]) then raise exception 'January 31 drifted into February'; end if;
  if not public.crm_schedule_booking_recurrence_hits_block('2026-01-31',null,'monthly','2026-03-31','2026-03-31',array[2]::smallint[]) then raise exception 'March 31 occurrence missed'; end if;
  if public.crm_schedule_booking_recurrence_hits_block('2026-01-01','2026-02-01','daily','2027-01-01','2027-12-31',array[1,2,3,4,5,6,7]::smallint[]) then raise exception 'disjoint finite recurrence matched'; end if;
  if public.crm_canonical_room_name('Зал 1') <> public.crm_canonical_room_name('  зал   1  ') then raise exception 'room spaces/case not canonical'; end if;
  if public.crm_canonical_room_name(E'\tЗал\n  1\t') <> public.crm_canonical_room_name('зал 1') then raise exception 'room whitespace not canonical'; end if;
  if public.crm_canonical_room_name('Зал 1') = public.crm_canonical_room_name('Зал 2') then raise exception 'different rooms matched'; end if;
  if not (false or public.crm_canonical_room_name('Зал 1')=public.crm_canonical_room_name(' зал  1 ')) then raise exception 'selected-room canonical predicate failed'; end if;
  if not (true or public.crm_canonical_room_name('Зал 1')=public.crm_canonical_room_name('Інша')) then raise exception 'all-room predicate changed'; end if;
  if not public.crm_schedule_booking_recurrence_hits_block('2026-10-02','2026-01-01','none','2026-10-02','2026-10-02',array[5]::smallint[]) then raise exception 'stale until bypassed one-off block'; end if;
  if not public.crm_schedule_booking_recurrence_hits_block('2026-10-02','2026-01-01','crafted','2026-10-02','2026-10-02',array[5]::smallint[]) then raise exception 'unknown recurrence did not behave as one-off'; end if;
  if public.crm_schedule_booking_recurrence_hits_block('2026-10-01','2026-01-01','none','2026-10-02','2026-10-02',array[4]::smallint[]) then raise exception 'one-off outside block matched'; end if;
  if public.crm_schedule_booking_recurrence_hits_block('2026-10-02','2026-01-01','none','2026-10-02','2026-10-02',array[1]::smallint[]) then raise exception 'one-off ignored block weekday'; end if;
  if public.crm_schedule_booking_recurrence_hits_block('2026-10-02','2026-10-01','daily','2026-10-02','2026-10-02',array[5]::smallint[]) then raise exception 'daily ignored recurrence end'; end if;
  if public.crm_schedule_booking_recurrence_hits_block('2026-10-02','2026-10-01','weekly','2026-10-02','2026-10-02',array[5]::smallint[]) then raise exception 'weekly ignored recurrence end'; end if;
  if public.crm_schedule_booking_recurrence_hits_block('2026-10-02','2026-10-01','monthly','2026-10-02','2026-10-02',array[5]::smallint[]) then raise exception 'monthly ignored recurrence end'; end if;
  if not (public.crm_canonical_room_name('Зал 1')=public.crm_canonical_room_name(' зал  1 ') and public.crm_schedule_booking_recurrence_hits_block('2026-10-02','2026-01-01','none','2026-10-02','2026-10-02',array[5]::smallint[])) then raise exception 'selected-room stale-until bypass'; end if;
  if not (true and public.crm_schedule_booking_recurrence_hits_block('2026-10-02','2026-01-01','none','2026-10-02','2026-10-02',array[5]::smallint[])) then raise exception 'all-room stale-until bypass'; end if;
  if position('crm.booking_block_override' in pg_get_functiondef('public.crm_enforce_schedule_booking_blocks()'::regprocedure))=0 then raise exception 'trigger does not require explicit override context'; end if;
  if position('crm_is_admin_session() or coalesce(new.status' in pg_get_functiondef('public.crm_enforce_schedule_booking_blocks()'::regprocedure))>0 then raise exception 'unconditional admin bypass remains'; end if;
  if not exists(select 1 from pg_proc where oid='public.crm_admin_override_create_room_booking(date,text,text,text,text,text,text,text,integer,integer,text,text,text,text,text,date,text,text,text)'::regprocedure and prosecdef and array_to_string(proconfig,',') like '%search_path=public%') then raise exception 'create override RPC hardening missing'; end if;
  if not exists(select 1 from pg_proc where oid='public.crm_admin_override_update_room_booking(uuid,date,text,text,text,text,text,text,text,integer,integer,text,text,text,text,text,date,text,text,text)'::regprocedure and prosecdef and array_to_string(proconfig,',') like '%search_path=public%') then raise exception 'update override RPC hardening missing'; end if;
  if has_function_privilege('anon','public.crm_admin_override_create_room_booking(date,text,text,text,text,text,text,text,integer,integer,text,text,text,text,text,date,text,text,text)','execute') then raise exception 'anon can call create override'; end if;
  if has_function_privilege('anon','public.crm_admin_override_update_room_booking(uuid,date,text,text,text,text,text,text,text,integer,integer,text,text,text,text,text,date,text,text,text)','execute') then raise exception 'anon can call update override'; end if;
  if position('crm.room_rename_old_name' in pg_get_functiondef('public.rename_studio_room(uuid,text)'::regprocedure))=0 or position('crm.room_rename_new_name' in pg_get_functiondef('public.rename_studio_room(uuid,text)'::regprocedure))=0 then raise exception 'rename cascade context missing'; end if;
  if not exists(select 1 from pg_proc where oid='public.rename_studio_room(uuid,text)'::regprocedure and prosecdef and array_to_string(proconfig,',') like '%search_path=pg_catalog, public%') then raise exception 'rename RPC hardening missing'; end if;
  perform set_config('crm.booking_block_override','off',true);
  if current_setting('crm.booking_block_override',true)<>'off' then raise exception 'override context setup broken'; end if;
  perform set_config('crm.booking_block_override','on',true);
  if current_setting('crm.booking_block_override',true)<>'on' then raise exception 'transaction-local override unavailable'; end if;
  perform set_config('crm.booking_block_override','off',true);
end $$;
rollback;
