import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";

const name = "20261002090000_schedule_booking_blocks.sql";
const sql = readFileSync(new URL(`../supabase/migrations/${name}`, import.meta.url), "utf8");
test("booking-block migration remains the latest timestamp", () => { assert.equal(readdirSync(new URL("../supabase/migrations", import.meta.url)).filter(x=>x.endsWith(".sql")).sort().at(-1), name); });
test("migration preserves access and trigger invariants", () => {
  for (const required of ["enable row level security", "crm_is_admin_session()", "crm_is_active_trainer_session()", "security definer", "set search_path", "before insert or update", "new.start_time::time < b.end_time", "b.start_time < new.end_time::time", "revoke all", "grant execute"]) assert.match(sql.toLowerCase(), new RegExp(required.replace(/[()]/g, "\\$&")));
  assert.doesNotMatch(sql, /service_role|ip_address|token|secret/i);
});
test("open-ended recurrence uses bounded mode-specific candidates", () => { assert.match(sql, /crm_schedule_booking_recurrence_hits_block/); assert.match(sql, /for i in 0\.\.least\(6,v_to-v_from\)/i); assert.match(sql, /\(\(\(v_offset\+6\)\/7\)\*7\)/i); assert.match(sql, /while v_month <= date_trunc\('month',v_to\)/i); assert.doesNotMatch(sql, /generate_series\([\s\S]*interval '1 day'/i); });
test("mutations preserve canonical room links without a failure-prone post-commit fetch", () => { const db=readFileSync(new URL("../src/db.js",import.meta.url),"utf8"); assert.doesNotMatch(db,/fetchSavedScheduleBookingBlock/); assert.match(db,/room_ids: block\.allRooms \? \[\] : block\.roomIds/); assert.match(db,/return requireBlockId\(data, 'Створення', block\)/); });
test("trigger canonicalizes names and requires transaction-local explicit admin override", () => { assert.match(sql,/crm_canonical_room_name\(r\.name\)=public\.crm_canonical_room_name\(new\.room_name\)/); assert.match(sql,/regexp_replace\(coalesce\(p_name,''\),'\[\[:space:\]\]\+'/); assert.doesNotMatch(sql,/if public\.crm_is_admin_session\(\) or coalesce\(new\.status/); assert.match(sql,/current_setting\('crm\.booking_block_override',true\)='on'/); assert.match(sql,/set_config\('crm\.booking_block_override','on',true\)/); });
test("override RPCs whitelist fields and are admin checked", () => { assert.match(sql,/crm_admin_override_create_room_booking\([\s\S]*p_date date[\s\S]*if not public\.crm_is_admin_session\(\)/); assert.match(sql,/crm_admin_override_update_room_booking\([\s\S]*p_id uuid[\s\S]*if not public\.crm_is_admin_session\(\)/); assert.doesNotMatch(sql,/crm_admin_override_(?:create|update)_room_booking\([^)]*(?:json|jsonb)/); });
test("room rename bypass is scoped to the canonical admin RPC and restores context", () => { assert.match(sql,/create or replace function public\.rename_studio_room[\s\S]*if not public\.crm_is_admin_session\(\)/); assert.match(sql,/crm\.room_rename_old_name/); assert.match(sql,/exception when others then[\s\S]*v_previous_old[\s\S]*raise/); assert.match(sql,/new\.date is not distinct from old\.date[\s\S]*new\.status is not distinct from old\.status/); });
test("one-off and unknown recurrence branch before recurrence end bounds", () => { const branch=sql.indexOf("if v_mode not in ('daily','weekly','monthly')"); const bound=sql.indexOf("v_to := least(coalesce(p_until,p_block_end),p_block_end)"); assert.ok(branch>0 && bound>branch); assert.doesNotMatch(sql.slice(branch,bound),/p_until/); });
